import { invoke } from '@tauri-apps/api/core';
import type {
  DocumentListItem, DocumentRevision, ActivityEntry, DocumentFileInfo,
} from '../types/document';

export async function listDocuments(currentUserId: number): Promise<DocumentListItem[]> {
  return invoke<DocumentListItem[]>('list_documents', { currentUserId });
}

export async function getDocument(currentUserId: number, documentId: number): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('get_document', { currentUserId, documentId });
}

/**
 * No approval date is passed. It used to be, and the backend bound it into
 * effective_date — so the form's "Approval Date" never reached the column the
 * product reads. Approval dates are now written only by approveDocument.
 */
export async function createDocument(
  currentUserId: number,
  title: string,
  documentType: string,
  version: string,
  ownerUserId: number | null,
  description: string | null,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('create_document', {
    currentUserId, title, documentType, version, ownerUserId, description,
  });
}

export async function updateDocument(
  currentUserId: number,
  documentId: number,
  title: string,
  documentType: string,
  version: string,
  ownerUserId: number | null,
  description: string | null,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('update_document', {
    currentUserId, documentId, title, documentType, version, ownerUserId, description,
  });
}

export async function setDocumentStatus(
  currentUserId: number,
  documentId: number,
  status: string,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('set_document_status', { currentUserId, documentId, status });
}

export async function attachDocumentFile(
  currentUserId: number,
  documentId: number,
  sourcePath: string,
  originalFileName: string,
  changeSummary: string | null,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('attach_document_file', {
    currentUserId, documentId, sourcePath, originalFileName, changeSummary,
  });
}

export async function listDocumentRevisions(
  currentUserId: number,
  documentId: number,
): Promise<DocumentRevision[]> {
  return invoke<DocumentRevision[]>('list_document_revisions', { currentUserId, documentId });
}

export async function getDocumentActivity(
  currentUserId: number,
  documentId: number,
): Promise<ActivityEntry[]> {
  return invoke<ActivityEntry[]>('get_document_activity', { currentUserId, documentId });
}

export async function openDocumentFile(currentUserId: number, documentId: number): Promise<void> {
  return invoke('open_document_file', { currentUserId, documentId });
}

// ── Stage 4: viewing, attachment lifecycle, approval ─────────────────────────

/** Describe the attached file so the UI can choose preview vs external open. */
export async function getDocumentFileInfo(
  currentUserId: number,
  documentId: number,
): Promise<DocumentFileInfo> {
  return invoke<DocumentFileInfo>('get_document_file_info', { currentUserId, documentId });
}

/**
 * Fetch the document's bytes for the in-app viewer.
 *
 * Requested by document id, never by path: the backend resolves the managed file
 * itself, so there is no URL or filesystem handle for the renderer to redirect.
 * Tauri returns the raw body as an ArrayBuffer.
 */
export async function readDocumentFile(
  currentUserId: number,
  documentId: number,
): Promise<Uint8Array> {
  const body = await invoke<ArrayBuffer | number[]>('read_document_file', {
    currentUserId, documentId,
  });
  return body instanceof ArrayBuffer ? new Uint8Array(body) : new Uint8Array(body);
}

export async function printDocumentFile(currentUserId: number, documentId: number): Promise<void> {
  return invoke('print_document_file', { currentUserId, documentId });
}

/** Detach and delete a draft document's file. Refused once the document is controlled. */
export async function removeDocumentAttachment(
  currentUserId: number,
  documentId: number,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('remove_document_attachment', { currentUserId, documentId });
}

/** Approve into CONTROLLED. The approval date is generated by the backend. */
export async function approveDocument(
  currentUserId: number,
  documentId: number,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('approve_document', { currentUserId, documentId });
}

/** Reject for correction. The reason is required and is kept with the document. */
export async function rejectDocument(
  currentUserId: number,
  documentId: number,
  reason: string,
): Promise<DocumentListItem> {
  return invoke<DocumentListItem>('reject_document', { currentUserId, documentId, reason });
}

