use std::fs;
use std::path::{Path, PathBuf};

const APP_DIR_NAME: &str = "QMSDesktop";

pub struct StoragePaths {
    pub root: PathBuf,
    pub database: PathBuf,
    pub settings: PathBuf,
    pub license: PathBuf,
    pub uploads_documents: PathBuf,
    pub uploads_capa: PathBuf,
    pub uploads_risks: PathBuf,
    pub uploads_complaints: PathBuf,
    pub uploads_audits: PathBuf,
    pub uploads_nc: PathBuf,
    pub backups: PathBuf,
}

/// Resolve %APPDATA%\QMSDesktop on Windows. QMS Desktop is a Windows-only product.
pub fn get_app_storage_root() -> Result<PathBuf, String> {
    let appdata = std::env::var("APPDATA")
        .map_err(|_| "APPDATA environment variable not set".to_string())?;
    Ok(PathBuf::from(appdata).join(APP_DIR_NAME))
}

pub fn get_storage_paths() -> Result<StoragePaths, String> {
    let root = get_app_storage_root()?;
    Ok(StoragePaths {
        database:           root.join("data.db"),
        settings:           root.join("settings.json"),
        license:            root.join("license.json"),
        uploads_documents:  root.join("uploads").join("documents"),
        uploads_capa:       root.join("uploads").join("capa"),
        uploads_risks:      root.join("uploads").join("risks"),
        uploads_complaints: root.join("uploads").join("complaints"),
        uploads_audits:     root.join("uploads").join("audits"),
        uploads_nc:         root.join("uploads").join("nc"),
        backups:            root.join("backups"),
        root,
    })
}

pub fn create_storage_directories(paths: &StoragePaths) -> Result<(), String> {
    let dirs = [
        &paths.root,
        &paths.uploads_documents,
        &paths.uploads_capa,
        &paths.uploads_risks,
        &paths.uploads_complaints,
        &paths.uploads_audits,
        &paths.uploads_nc,
        &paths.backups,
    ];
    for dir in &dirs {
        fs::create_dir_all(dir)
            .map_err(|e| format!("Failed to create directory {:?}: {}", dir, e))?;
    }
    Ok(())
}

/// Create settings.json and license.json with minimal placeholder content if they do not exist.
pub fn create_placeholder_files(paths: &StoragePaths) -> Result<(), String> {
    if !paths.settings.exists() {
        let content = r#"{"company_name":"","company_logo_path":"","timezone":"UTC","date_format":"YYYY-MM-DD"}"#;
        fs::write(&paths.settings, content)
            .map_err(|e| format!("Failed to create settings.json: {}", e))?;
    }
    if !paths.license.exists() {
        let content = r#"{"status":"unlicensed","activated_at":null,"hardware_id":null,"token":null}"#;
        fs::write(&paths.license, content)
            .map_err(|e| format!("Failed to create license.json: {}", e))?;
    }
    Ok(())
}

pub fn uploads_initialized(paths: &StoragePaths) -> bool {
    paths.uploads_documents.exists()
        && paths.uploads_capa.exists()
        && paths.uploads_risks.exists()
        && paths.uploads_complaints.exists()
        && paths.uploads_audits.exists()
        && paths.uploads_nc.exists()
        && paths.backups.exists()
}

// ── Managed-storage path safety ───────────────────────────────────────────────

/// Resolve a STORED FILENAME into a real path inside a managed uploads directory.
///
/// Every attachment operation must go through this. The database holds a bare
/// filename (`{document_id}_{micros}.{ext}`, generated by the backend), never a
/// path, and the directory comes from `get_storage_paths` — so nothing a caller
/// sends is ever concatenated into a location. This function exists to make that
/// guarantee explicit and to fail loudly if the invariant is ever broken, for
/// example by a hand-edited database row.
///
/// Both sides are canonicalised before comparison. A textual prefix check would
/// be wrong on Windows: `C:\Users\x\AppData\Roaming\QMSDesktop\uploads\documents`
/// and a junction pointing elsewhere can share a prefix while resolving to
/// different places, and `..`, mixed separators, short (8.3) names and
/// case differences all defeat string matching. `canonicalize` resolves symlinks,
/// junctions, relative segments and short names to one true form.
///
/// The file must already exist — canonicalisation of a missing path fails — which
/// is correct here: every caller is acting on an attachment that should be on
/// disk, and "not there" is a state they must handle explicitly rather than a
/// path to be constructed.
pub fn resolve_managed_file(dir: &Path, stored_filename: &str) -> Result<PathBuf, String> {
    // A stored value that is not a bare filename never came from this app.
    if stored_filename.trim().is_empty() {
        return Err("No file is attached".to_string());
    }
    if stored_filename.contains('/')
        || stored_filename.contains('\\')
        || stored_filename.contains(':')
        || stored_filename.contains('\0')
        || stored_filename.contains("..")
    {
        return Err("Stored file reference is not a plain file name".to_string());
    }

    let candidate = dir.join(stored_filename);
    if !candidate.exists() {
        return Err("File not found on disk. It may have been moved or deleted.".to_string());
    }

    let real_file = candidate
        .canonicalize()
        .map_err(|e| format!("Could not resolve the stored file: {}", e))?;
    let real_dir = dir
        .canonicalize()
        .map_err(|e| format!("Could not resolve the storage directory: {}", e))?;

    // Compare resolved ancestry, not text.
    if !real_file.starts_with(&real_dir) {
        return Err("Refusing to operate on a file outside managed storage".to_string());
    }
    if !real_file.is_file() {
        return Err("The stored attachment is not a regular file".to_string());
    }

    Ok(real_file)
}

/// Validate a user-selected IMPORT source before it is copied into managed
/// storage.
///
/// This path legitimately comes from the renderer, because the user picked it in
/// a native dialog. It is only ever READ, and only ever copied inward — nothing
/// downstream will write to or delete it. What is checked here is that it is a
/// real, regular, readable file rather than a directory, a device path, or a
/// dangling link that would make the copy behave unexpectedly.
pub fn validate_import_source(source_path: &str) -> Result<PathBuf, String> {
    let p = Path::new(source_path);
    if !p.is_absolute() {
        return Err("The selected file path is not absolute".to_string());
    }
    let real = p
        .canonicalize()
        .map_err(|_| "Source file does not exist".to_string())?;
    if !real.is_file() {
        return Err("The selected item is not a file".to_string());
    }
    Ok(real)
}

#[cfg(test)]
mod safepath_tests {
    use super::*;
    use std::fs;

    fn tmp(tag: &str) -> PathBuf {
        let mut d = std::env::temp_dir();
        d.push(format!("qms_safepath_{}_{}", tag, std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(d.join("managed")).unwrap();
        fs::create_dir_all(d.join("elsewhere")).unwrap();
        d
    }

    #[test]
    fn a_managed_file_resolves() {
        let d = tmp("ok");
        let managed = d.join("managed");
        fs::write(managed.join("1_123.pdf"), b"%PDF-1.4").unwrap();

        let got = resolve_managed_file(&managed, "1_123.pdf").unwrap();
        assert!(got.ends_with("1_123.pdf"));
        assert!(got.is_file());

        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn traversal_out_of_managed_storage_is_refused() {
        let d = tmp("traverse");
        let managed = d.join("managed");
        fs::write(d.join("elsewhere").join("secret.pdf"), b"x").unwrap();

        // The obvious escape, and the encodings that defeat a string prefix check.
        for evil in [
            "../elsewhere/secret.pdf",
            "..\\elsewhere\\secret.pdf",
            "../../Windows/System32/drivers/etc/hosts",
            "sub/nested.pdf",
            "sub\\nested.pdf",
            "C:\\Windows\\System32\\calc.exe",
            "",
            "   ",
        ] {
            assert!(
                resolve_managed_file(&managed, evil).is_err(),
                "{:?} should have been refused",
                evil,
            );
        }

        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn a_missing_file_is_reported_not_fabricated() {
        let d = tmp("missing");
        let err = resolve_managed_file(&d.join("managed"), "9_9.pdf").unwrap_err();
        assert!(err.contains("not found"), "unexpected: {}", err);
        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn a_directory_is_not_an_attachment() {
        let d = tmp("dir");
        let managed = d.join("managed");
        fs::create_dir_all(managed.join("notafile.pdf")).unwrap();
        assert!(resolve_managed_file(&managed, "notafile.pdf").is_err());
        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn an_import_source_must_be_an_existing_regular_file() {
        let d = tmp("import");
        let f = d.join("elsewhere").join("pick.pdf");
        fs::write(&f, b"x").unwrap();

        assert!(validate_import_source(f.to_str().unwrap()).is_ok());
        assert!(validate_import_source("relative/path.pdf").is_err());
        assert!(validate_import_source(d.join("elsewhere").to_str().unwrap()).is_err());
        assert!(validate_import_source(d.join("nope.pdf").to_str().unwrap()).is_err());

        let _ = fs::remove_dir_all(&d);
    }
}
